---
# https://github.com/github/safe-settings/blob/main-enterprise/docs/sample-settings/settings.yml
repository:
  allow_squash_merge: false
  allow_merge_commit: true
  allow_rebase_merge: false
  allow_auto_merge: true
  delete_branch_on_merge: true

# rulesets can have exceptions for flowzone-app to bypass policies
# https://github.com/github/safe-settings/blob/main-enterprise/docs/sample-settings/org-ruleset.yml
rulesets:
  - name: "policy-bot: main"
    target: branch
    enforcement: active
    conditions:
      ref_name:
        include:
          - refs/heads/main
        exclude: []
      repository_name:
        include:
          - ~ALL
        exclude: []
    rules:
      - type: required_status_checks
        parameters:
          strict_required_status_checks_policy: true
          required_status_checks:
            - context: "policy-bot: main"
              integration_id: 278558
      - type: pull_request
        parameters:
          required_approving_review_count: 0
          dismiss_stale_reviews_on_push: false
          require_code_owner_review: false
          require_last_push_approval: false
          required_review_thread_resolution: false
    bypass_actors:
      - actor_id: 1
        actor_type: OrganizationAdmin
        bypass_mode: always
      - actor_id: 5
        actor_type: RepositoryRole
        bypass_mode: always
      - actor_id: 291899
        actor_type: Integration
        bypass_mode: always

  - name: "policy-bot: master"
    target: branch
    enforcement: active
    conditions:
      ref_name:
        include:
          - refs/heads/master
        exclude: []
      repository_name:
        include:
          - ~ALL
        exclude: []
    rules:
      - type: required_status_checks
        parameters:
          strict_required_status_checks_policy: true
          required_status_checks:
            - context: "policy-bot: master"
              integration_id: 278558
      - type: pull_request
        parameters:
          required_approving_review_count: 0
          dismiss_stale_reviews_on_push: false
          require_code_owner_review: false
          require_last_push_approval: false
          required_review_thread_resolution: false
    bypass_actors:
      - actor_id: 1
        actor_type: OrganizationAdmin
        bypass_mode: always
      - actor_id: 5
        actor_type: RepositoryRole
        bypass_mode: always
      - actor_id: 291899
        actor_type: Integration
        bypass_mode: always
